frameworkVersion: '3.22.0'

service: payment

params: ${file(./environment/params.yml)}

provider: ${file(./environment/provider.yml)}

plugins:
  - serverless-plugin-datadog
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-aws-eventbridge

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3008
  cors: ${file(./environment/cors.yml)}
  datadog: ${file(./environment/datadog.yml)}
  serverless-offline-aws-eventbridge:
    port: 5010 # port to run the eventBridge mock server on
    mockEventBridgeServer: false # Set to false if EventBridge is already mocked by another stack
    pubSubPort: 4081 # Port to run the MQ server (or just listen if using an EventBridge Mock server from another stack)
  
package:
  individually: true
  exclude:
    - '.*/**'
    - 'node_modules'

functions:
  create:
    description: Checkout - Instance a payment plan from sns
    handler: src/handler/payment.create
    memorySize: ${param:aws-memory-size-medium}
    timeout: ${param:aws-timeout-medium}
    events:
      - sns: ${param:sns-order-completed-arn}

  installments-get:
    description: Recurring - Get a installment plan
    handler: src/handler/payment.getInstallments
    memorySize: ${param:aws-memory-size-medium}
    events:
      - http:
          path: /{id}/installments/{installment}
          method: get
          cors: true
          private: true

  integration-update:
    description: Update a sales order within a payment plan
    handler: src/handler/payment.soUpdate
    memorySize: ${param:aws-memory-size-medium}
    events:
      - eventBridge:
          pattern:
            source:
              - 'billing-so'
            detail-type:
              - 'payment-update'

  masive-cancel:
    description: Recurring - Masive cancel plans programatically
    handler: src/handler/payment.cancel
    memorySize: ${param:aws-memory-size-high}
    timeout: ${param:aws-timeout-high}
    events:
      - http:
          path: /plans/cancel
          method: patch
          cors: true
          private: true

  masive-update-price:
    description: Recurring - Masive update plan price programatically
    handler: src/handler/payment.updatePrice
    memorySize: ${param:aws-memory-size-high}
    timeout: ${param:aws-timeout-high}
    events:
      - http:
          path: /plans/update-price
          method: patch
          cors: true
          private: true

  masive-create:
    description: Recurring - Masive create plans programatically
    handler: src/handler/payment.createPlans
    memorySize: ${param:aws-memory-size-high}
    timeout: ${param:aws-timeout-high}
    events:
      - http:
          path: /plans/create
          method: post
          cors: true
          private: true

  masive-installments:
    description: Checkout - Instance a payment plan per order
    handler: src/handler/payment.createMany
    memorySize: ${param:aws-memory-size-high}
    timeout: ${param:aws-timeout-high}
    events:
      - http:
          path: /create/installments
          method: post
          cors: true
          private: true

  plan-get:
    description: Recurring - Get a payment plan
    handler: src/handler/payment.get
    memorySize: ${param:aws-memory-size-medium}
    events:
      - http:
          path: /{id}
          method: get
          cors: true
          private: true

  plan-get-all:
    description: Recurring - Get plans by user id
    handler: src/handler/payment.getAll
    memorySize: ${param:aws-memory-size-medium}
    events:
      - http:
          path: /plans/{userId}
          method: get
          cors: true
          private: true

  process-pay:
    handler: src/handler/payment.processEvent
    description: Recurring - process payments
    memorySize: ${param:aws-memory-size-high}
    timeout: ${param:aws-timeout-high}
    events:
      - eventBridge:
          eventBus: ${param:recurring-bus-arn}
          pattern:
            source:
              - recurring.process.gateway.event
              
  track-payment-processed:
    handler: src/handler/payment.trackPaymentProcessed
    description: Recurring - track segment event
    memorySize: ${param:aws-memory-size-medium}
    timeout: ${param:aws-timeout-medium}
    events:
      - eventBridge:
          eventBus: ${param:recurring-bus-arn}
          pattern:
            source:
              - recurring.process.gateway.event

  process-response:
    description: Recurring - Process payment response
    handler: src/handler/payment.processResponse
    memorySize: ${param:aws-memory-size-medium}
    events:
      - http:
          path: /process
          method: post
          cors: true
          private: true

  student-abandon-status-change:
    handler: src/handler/plan.statusChange
    description: Recurring - Student status change to abandon or abandon request
    memorySize: ${param:aws-memory-size-medium}
    timeout: ${param:aws-timeout-low}
    events:
      - eventBridge:
          pattern:
            source:
              - stage-machine
            detail-type:
              - stage-change
            detail:
              resource_type: [1] # student
              stage_id: [6, 13, 14] # abandoned, abandoned_admission, abandon_request 

  student-studying-status-change:
    handler: src/handler/plan.statusChange
    description: Recurring - Student status change from abandon request to studying 
    memorySize: ${param:aws-memory-size-medium}
    timeout: ${param:aws-timeout-low}
    events:
      - eventBridge:
          pattern:
            source:
              - stage-machine
            detail-type:
              - stage-change
            detail:
              resource_type: [1] # student
              stage_id: [2] # studying 
              previous_stage_id: [14] # abandon_request